# Generated by Django 5.1.7 on 2025-03-26 16:56

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mymodel',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('big_integer_field', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=255)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_field', models.DurationField(default=datetime.timedelta(days=1))),
                ('file_field', models.FileField(default=1, upload_to='')),
                ('float_field', models.FloatField(default=1.1)),
                ('image_field', models.ImageField(default='myimage', upload_to='')),
                ('generic_ip_address_field', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
                ('integer_field', models.IntegerField(default=0)),
                ('json_field', models.JSONField(blank=True, default=dict, null=True)),
                ('null_boolean_field', models.BooleanField(blank=True, null=True)),
                ('positive_big_integer_field', models.PositiveBigIntegerField(default=1)),
                ('positive_integer_field', models.PositiveIntegerField(default=1)),
                ('positive_small_integer_field', models.PositiveSmallIntegerField(default=1)),
                ('small_integer_field', models.SmallIntegerField(default=0)),
                ('slug_field', models.SlugField(blank=True, default='')),
                ('url_field', models.URLField(blank=True, default='', null=True)),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
